apiVersion: apps/v1
kind: Deployment
metadata:
  name: service1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: service1
  template:
    metadata:
      labels:
        app: service1
    spec:
      containers:
        - name: service1
          image: "{{ .Values.service1.repository }}:{{ .Values.service1.tag }}"
          ports:
            - containerPort: 8080  
